### ISSUE TITLE
测试查询接口时，一直返回接口请求报文核验失败

### ISSUE THREAD

**Issue by uuidcoder** [chinawilon/fcm_game#1]
{"errcode":1012,"errmsg":"SYS REQ PARAM CHECK ERROR"}

实名认证接口和戏用户行为数据上报接口都是通过的，就实名认证结果查询接口错误

**Comment by chinawilon** [comment]
麻烦贴下debug的info信息，使用```flushInfo()```

**Comment by uuidcoder** [comment]
|  
-- | --
  | {"errcode":1012,"errmsg":"SYS REQ PARAM CHECK ERROR"}
  | [2021-03-09 01:41:16] GET: https://wlc.nppa.gov.cn/test/authentication/query/FreMKm
  | [2021-03-09 01:41:16] makeSign-before: xxxxxxxxappIdxxxxxxbizId1101999999timestamps1615254076236{"data":"ExOaloRhE+kswMd/GexytJyzB3R6YArPKn9SSBty2pam75BPh+qZ/QGmwk+YRZuaoe4uMYmYGQ"}
  | [2021-03-09 01:41:16] makeSign-after: 5e876a00ac00da4eae70cfdbe3b1c79a04c8447b6b212adec46b66ade27990ac
  | [2021-03-09 01:41:16] raw: {"ai":"100000000000000001"}
  | [2021-03-09 01:41:16] options: Array
  | (
  | [headers] => Array
  | (
  | [appId] => xxxxxx
  | [bizId] => 1101999999
  | [timestamps] => 1615254076236
  | [sign] => 5e876a00ac00da4eae70cfdbe3b1c79a04c8447b6b212adec46b66ade27990ac
  | )
  |  
  | [body] => {"data":"ExOaloRhE+kswMd/GexytJyzB3R6YArPKn9SSBty2pam75BPh+qZ/QGmwk+YRZuaoe4uMYmYGQ"}
  | [timeout] => 20
  | )
  |  
  |  
  |

**Comment by chinawilon** [comment]
已修复: https://github.com/chinawilon/fcm_game/commit/7a771e205421ed26d93ceba22193a34daf3a3fa7

**Comment by uuidcoder** [comment]
还是不行


  |  
-- | --
  | {"errcode":1011,"errmsg":"SYS REQ PARTNER AUTH ERROR"}
  | [2021-03-09 06:47:48] GET: https://wlc.nppa.gov.cn/test/authentication/query/xNr2HV
  | [2021-03-09 06:47:48] makeSign-before: xxxxxappIdxxxxxbizId1101999999timestamps1615272468128{"data":"mCnKIolbOheIyGmbIHZ1opwGk/twXbri+QD0xOrDlT93E/3ghd7/IkAI9CKV1agrs2261uwTOA"}
  | [2021-03-09 06:47:48] makeSign-after: 3a5facca40f7b51d189c2a878a02c36355a7d464040900b9ba510cf4c647858e
  | [2021-03-09 06:47:48] raw: {"ai":"100000000000000001"}
  | [2021-03-09 06:47:48] options: Array
  | (
  | [headers] => Array
  | (
  | [appId] => xxxxxx
  | [bizId] => 1101999999
  | [timestamps] => 1615272468128
  | [sign] => 3a5facca40f7b51d189c2a878a02c36355a7d464040900b9ba510cf4c647858e
  | )
  |  
  | [body] => {"data":"mCnKIolbOheIyGmbIHZ1opwGk/twXbri+QD0xOrDlT93E/3ghd7/IkAI9CKV1agrs2261uwTOA"}
  | [timeout] => 20
  | [query] => Array
  | (
  | [ai] => 100000000000000001
  | )
  |  
  | )
  |  
  |  
  |

**Comment by uuidcoder** [comment]
问了官方的技术，回复如下：
查询接口需要将ai作为“业务参数”生成sign，没有body，生成sign时不需要{"data":"yIyNebzqNn6l/Ud5ggHmy6p3ThlGeE2wEmeS+3fKsokYKIo2BOuxjzavF6uTaF8BnbJ3WUrdug"}

**Comment by uuidcoder** [comment]
我知道错误在哪里了，在makeSign第二个参数没有传入['ai'='xxx']

**Comment by uuidcoder** [comment]
上面说的生成sign不需要body是错误的

**Comment by uuidcoder** [comment]
这样就可以了
```
private function doRequest(string $method, string $uri, array $headers=[], array $body = [], array $options = [])
    {
        $this->info(sprintf("%s: %s", $method, $uri));
        $raw = json_encode($body, JSON_UNESCAPED_UNICODE);
        $query = isset($options['query']) ? $options['query'] : [];
        $body = '{"data":"' . $this->aes->encrypt($raw) . '"}';
        $headers = array_merge($this->headers, $headers);
        $headers['sign'] = $this->makeSign($body, $query);
        $options = array_merge(['headers'=>$headers, 'body'=>$body, 'timeout'=>$this->timeout], $options);
        $this->info(sprintf("%s: %s", 'raw', $raw));
        $this->info(sprintf("%s: %s", 'options', print_r($options, true)));
        $response = $this->http->request($method, $uri, $options);
        return $response->getBody()->getContents();
    }
```

**Comment by chinawilon** [comment]
已合并
